#############################################################################
# Makefile for building: finalNewBe
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  finalNewBe.pro
# Template: app
# Command: /home/ohmic/Qt5.5.1_Desktop32Bit_out2/bin/qmake -spec linux-g++-32 -o Makefile finalNewBe.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -m32 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m32 -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt5.5.1_Desktop32Bit_out2/include -I../../Qt5.5.1_Desktop32Bit_out2/include/QtQuick -I../../Qt5.5.1_Desktop32Bit_out2/include/QtGui -I../../Qt5.5.1_Desktop32Bit_out2/include/QtQml -I../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork -I../../Qt5.5.1_Desktop32Bit_out2/include/QtCore -I. -I../../Qt5.5.1_Desktop32Bit_out2/mkspecs/linux-g++-32
QMAKE         = /home/ohmic/Qt5.5.1_Desktop32Bit_out2/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = finalNewBe1.0.0
DISTDIR = /home/ohmic/internship-rahul/finalNewBe/.tmp/finalNewBe1.0.0
LINK          = g++
LFLAGS        = -m32 -Wl,-O1 -Wl,-rpath,/home/ohmic/Qt5.5.1_Desktop32Bit_out2/lib
LIBS          = $(SUBLIBS) -L/home/ohmic/Qt5.5.1_Desktop32Bit_out2/lib -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		signup.cpp \
		login.cpp \
		validation.cpp \
		csvrw.cpp \
		changepassword.cpp qrc_qml.cpp \
		moc_signup.cpp \
		moc_login.cpp \
		moc_validation.cpp \
		moc_csvrw.cpp \
		moc_changepassword.cpp
OBJECTS       = main.o \
		signup.o \
		login.o \
		validation.o \
		csvrw.o \
		changepassword.o \
		qrc_qml.o \
		moc_signup.o \
		moc_login.o \
		moc_validation.o \
		moc_csvrw.o \
		moc_changepassword.o
DIST          = ../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/spec_pre.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/unix.conf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/linux.conf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/sanitize.conf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/gcc-base.conf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/g++-base.conf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/g++-unix.conf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/qconfig.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/qt_functions.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/qt_config.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/linux-g++-32/qmake.conf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/spec_post.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/exclusive_builds.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/default_pre.prf \
		deployment.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/resolve_config.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/default_post.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/c++11.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/warn_on.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/qt.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/resources.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/moc.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/unix/opengl.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/unix/thread.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/testcase_targets.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/exceptions.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/yacc.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/lex.prf \
		finalNewBe.pro signup.h \
		login.h \
		validation.h \
		csvrw.h \
		changepassword.h main.cpp \
		signup.cpp \
		login.cpp \
		validation.cpp \
		csvrw.cpp \
		changepassword.cpp
QMAKE_TARGET  = finalNewBe
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = finalNewBe


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: finalNewBe.pro ../../Qt5.5.1_Desktop32Bit_out2/mkspecs/linux-g++-32/qmake.conf ../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/spec_pre.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/unix.conf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/linux.conf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/sanitize.conf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/gcc-base.conf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/g++-base.conf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/g++-unix.conf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/qconfig.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/qt_functions.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/qt_config.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/linux-g++-32/qmake.conf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/spec_post.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/exclusive_builds.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/default_pre.prf \
		deployment.pri \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/resolve_config.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/default_post.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/c++11.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/warn_on.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/qt.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/resources.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/moc.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/unix/opengl.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/unix/thread.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/testcase_targets.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/exceptions.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/yacc.prf \
		../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/lex.prf \
		finalNewBe.pro \
		qml.qrc \
		/home/ohmic/Qt5.5.1_Desktop32Bit_out2/lib/libQt5Quick.prl \
		/home/ohmic/Qt5.5.1_Desktop32Bit_out2/lib/libQt5Gui.prl \
		/home/ohmic/Qt5.5.1_Desktop32Bit_out2/lib/libQt5Qml.prl \
		/home/ohmic/Qt5.5.1_Desktop32Bit_out2/lib/libQt5Network.prl \
		/home/ohmic/Qt5.5.1_Desktop32Bit_out2/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++-32 -o Makefile finalNewBe.pro
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/spec_pre.prf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/unix.conf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/linux.conf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/sanitize.conf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/gcc-base.conf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/gcc-base-unix.conf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/g++-base.conf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/common/g++-unix.conf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/qconfig.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_core.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_declarative.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_help.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_location.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_location_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_network.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_script.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/qt_functions.prf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/qt_config.prf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/linux-g++-32/qmake.conf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/spec_post.prf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/exclusive_builds.prf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/default_pre.prf:
deployment.pri:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/resolve_config.prf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/default_post.prf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/c++11.prf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/warn_on.prf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/qt.prf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/resources.prf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/moc.prf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/unix/opengl.prf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/unix/thread.prf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/testcase_targets.prf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/exceptions.prf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/yacc.prf:
../../Qt5.5.1_Desktop32Bit_out2/mkspecs/features/lex.prf:
finalNewBe.pro:
qml.qrc:
/home/ohmic/Qt5.5.1_Desktop32Bit_out2/lib/libQt5Quick.prl:
/home/ohmic/Qt5.5.1_Desktop32Bit_out2/lib/libQt5Gui.prl:
/home/ohmic/Qt5.5.1_Desktop32Bit_out2/lib/libQt5Qml.prl:
/home/ohmic/Qt5.5.1_Desktop32Bit_out2/lib/libQt5Network.prl:
/home/ohmic/Qt5.5.1_Desktop32Bit_out2/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-32 -o Makefile finalNewBe.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents signup.h login.h validation.h csvrw.h changepassword.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp signup.cpp login.cpp validation.cpp csvrw.cpp changepassword.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		Poppins-Regular.ttf \
		logo.png \
		human.png \
		bg.png \
		Poppins-SemiBold.ttf \
		main.qml
	/home/ohmic/Qt5.5.1_Desktop32Bit_out2/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_signup.cpp moc_login.cpp moc_validation.cpp moc_csvrw.cpp moc_changepassword.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_signup.cpp moc_login.cpp moc_validation.cpp moc_csvrw.cpp moc_changepassword.cpp
moc_signup.cpp: ../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QObject \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnamespace.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobal.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qconfig.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfeatures.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsystemdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qprocessordetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcompilerdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypeinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypetraits.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsysinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlogging.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qflags.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbasicatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qgenericatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_cxx11.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_gcc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_msvc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv7.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv6.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv5.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_ia64.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_mips.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_x86.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_unix.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobalstatic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmutex.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnumeric.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstring.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qchar.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qrefcount.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qarraydata.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringbuilder.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qalgorithms.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qiterator.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearraylist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qregexp.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringmatcher.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcoreevent.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qscopedpointer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmetatype.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvarlengtharray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcontainerfwd.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qisenum.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject_impl.h \
		signup.h
	/home/ohmic/Qt5.5.1_Desktop32Bit_out2/bin/moc $(DEFINES) -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/mkspecs/linux-g++-32 -I/home/ohmic/internship-rahul/finalNewBe -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtQuick -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtGui -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtQml -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtNetwork -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtCore -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8/32 -I/usr/include/i386-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include signup.h -o moc_signup.cpp

moc_login.cpp: ../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QObject \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnamespace.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobal.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qconfig.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfeatures.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsystemdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qprocessordetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcompilerdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypeinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypetraits.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsysinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlogging.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qflags.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbasicatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qgenericatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_cxx11.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_gcc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_msvc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv7.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv6.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv5.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_ia64.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_mips.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_x86.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_unix.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobalstatic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmutex.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnumeric.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstring.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qchar.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qrefcount.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qarraydata.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringbuilder.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qalgorithms.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qiterator.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearraylist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qregexp.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringmatcher.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcoreevent.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qscopedpointer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmetatype.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvarlengtharray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcontainerfwd.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qisenum.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject_impl.h \
		login.h
	/home/ohmic/Qt5.5.1_Desktop32Bit_out2/bin/moc $(DEFINES) -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/mkspecs/linux-g++-32 -I/home/ohmic/internship-rahul/finalNewBe -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtQuick -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtGui -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtQml -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtNetwork -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtCore -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8/32 -I/usr/include/i386-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include login.h -o moc_login.cpp

moc_validation.cpp: ../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QObject \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnamespace.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobal.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qconfig.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfeatures.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsystemdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qprocessordetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcompilerdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypeinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypetraits.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsysinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlogging.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qflags.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbasicatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qgenericatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_cxx11.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_gcc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_msvc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv7.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv6.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv5.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_ia64.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_mips.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_x86.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_unix.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobalstatic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmutex.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnumeric.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstring.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qchar.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qrefcount.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qarraydata.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringbuilder.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qalgorithms.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qiterator.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearraylist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qregexp.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringmatcher.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcoreevent.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qscopedpointer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmetatype.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvarlengtharray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcontainerfwd.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qisenum.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QString \
		validation.h
	/home/ohmic/Qt5.5.1_Desktop32Bit_out2/bin/moc $(DEFINES) -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/mkspecs/linux-g++-32 -I/home/ohmic/internship-rahul/finalNewBe -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtQuick -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtGui -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtQml -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtNetwork -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtCore -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8/32 -I/usr/include/i386-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include validation.h -o moc_validation.cpp

moc_csvrw.cpp: ../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QObject \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnamespace.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobal.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qconfig.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfeatures.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsystemdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qprocessordetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcompilerdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypeinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypetraits.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsysinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlogging.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qflags.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbasicatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qgenericatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_cxx11.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_gcc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_msvc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv7.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv6.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv5.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_ia64.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_mips.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_x86.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_unix.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobalstatic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmutex.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnumeric.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstring.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qchar.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qrefcount.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qarraydata.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringbuilder.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qalgorithms.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qiterator.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearraylist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qregexp.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringmatcher.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcoreevent.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qscopedpointer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmetatype.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvarlengtharray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcontainerfwd.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qisenum.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QString \
		csvrw.h
	/home/ohmic/Qt5.5.1_Desktop32Bit_out2/bin/moc $(DEFINES) -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/mkspecs/linux-g++-32 -I/home/ohmic/internship-rahul/finalNewBe -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtQuick -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtGui -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtQml -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtNetwork -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtCore -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8/32 -I/usr/include/i386-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include csvrw.h -o moc_csvrw.cpp

moc_changepassword.cpp: ../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QObject \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnamespace.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobal.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qconfig.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfeatures.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsystemdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qprocessordetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcompilerdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypeinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypetraits.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsysinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlogging.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qflags.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbasicatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qgenericatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_cxx11.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_gcc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_msvc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv7.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv6.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv5.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_ia64.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_mips.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_x86.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_unix.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobalstatic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmutex.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnumeric.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstring.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qchar.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qrefcount.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qarraydata.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringbuilder.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qalgorithms.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qiterator.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearraylist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qregexp.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringmatcher.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcoreevent.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qscopedpointer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmetatype.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvarlengtharray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcontainerfwd.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qisenum.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject_impl.h \
		changepassword.h
	/home/ohmic/Qt5.5.1_Desktop32Bit_out2/bin/moc $(DEFINES) -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/mkspecs/linux-g++-32 -I/home/ohmic/internship-rahul/finalNewBe -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtQuick -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtGui -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtQml -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtNetwork -I/home/ohmic/Qt5.5.1_Desktop32Bit_out2/include/QtCore -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8/32 -I/usr/include/i386-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include changepassword.h -o moc_changepassword.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../Qt5.5.1_Desktop32Bit_out2/include/QtGui/QGuiApplication \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtGui/qguiapplication.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcoreapplication.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobal.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qconfig.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfeatures.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsystemdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qprocessordetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcompilerdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypeinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypetraits.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsysinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlogging.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qflags.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbasicatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qgenericatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_cxx11.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_gcc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_msvc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv7.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv6.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv5.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_ia64.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_mips.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_x86.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_unix.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobalstatic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmutex.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnumeric.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstring.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qchar.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qrefcount.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnamespace.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qarraydata.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringbuilder.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qalgorithms.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qiterator.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearraylist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qregexp.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringmatcher.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcoreevent.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qscopedpointer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmetatype.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvarlengtharray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcontainerfwd.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qisenum.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qeventloop.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtGui/qwindowdefs.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtGui/qwindowdefs_win.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtGui/qinputmethod.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlocale.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvariant.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmap.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qpair.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qdebug.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qhash.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtextstream.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qiodevice.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvector.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qpoint.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qset.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcontiguouscache.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qshareddata.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsize.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/QQmlApplicationEngine \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlapplicationengine.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlengine.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qurl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qurlquery.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qjsengine.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsharedpointer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qjsvalue.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qtqmlglobal.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlerror.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmldebug.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/QQmlContext \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlcontext.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/QtQml \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/QtQmlDepends \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QtCore \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QtCoreDepends \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qabstractanimation.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qanimationgroup.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qparallelanimationgroup.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qpauseanimation.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qpropertyanimation.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvariantanimation.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qeasingcurve.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsequentialanimationgroup.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtextcodec.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qendian.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlibraryinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qdatetime.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbuffer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qdatastream.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qdir.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfileinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfile.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfiledevice.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qdiriterator.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfileselector.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QObject \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QStringList \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfilesystemwatcher.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlockfile.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qloggingcategory.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qprocess.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qresource.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsavefile.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsettings.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstandardpaths.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstorageinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtemporarydir.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QScopedPointer \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtemporaryfile.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qabstractitemmodel.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qabstractproxymodel.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qidentityproxymodel.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qitemselectionmodel.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsortfilterproxymodel.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringlistmodel.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qjsonarray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qjsonvalue.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qjsondocument.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qjsonobject.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qabstracteventdispatcher.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qabstractnativeeventfilter.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbasictimer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmath.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmetaobject.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmimedata.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectcleanuphandler.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qpointer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsharedmemory.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsignalmapper.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsocketnotifier.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsystemsemaphore.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtimer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtranslator.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qwineventnotifier.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmimedatabase.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmimetype.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfactoryinterface.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlibrary.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qplugin.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qpluginloader.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/quuid.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qabstractstate.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qabstracttransition.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qeventtransition.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfinalstate.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qhistorystate.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsignaltransition.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstate.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstatemachine.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qexception.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfuture.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfutureinterface.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qrunnable.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qresultstore.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfuturesynchronizer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfuturewatcher.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qreadwritelock.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsemaphore.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qthread.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qthreadpool.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qthreadstorage.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qwaitcondition.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qarraydataops.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qarraydatapointer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbitarray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearraymatcher.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcache.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcollator.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcommandlineoption.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcommandlineparser.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcryptographichash.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qelapsedtimer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qline.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlinkedlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmargins.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmessageauthenticationcode.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qqueue.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qrect.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qregularexpression.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qscopedvaluerollback.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstack.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtextboundaryfinder.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtimeline.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtimezone.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qxmlstream.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtcoreversion.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/QtNetwork \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/QtNetworkDepends \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qabstractnetworkcache.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qnetworkrequest.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QSharedDataPointer \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QString \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QUrl \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QVariant \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qhttpmultipart.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QByteArray \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QIODevice \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/QNetworkRequest \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qnetworkaccessmanager.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/QSslConfiguration \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qsslconfiguration.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qsslsocket.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qtcpsocket.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qabstractsocket.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qsslerror.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qsslcertificate.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qssl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QFlags \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QtGlobal \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QMetaType \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qnetworkcookie.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QList \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qnetworkcookiejar.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qnetworkdiskcache.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qnetworkreply.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/QNetworkAccessManager \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qnetworkconfigmanager.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qnetworkconfiguration.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qnetworksession.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qnetworkinterface.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qhostaddress.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qauthenticator.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qdnslookup.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qhostinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qnetworkproxy.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qlocalserver.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qlocalsocket.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qtcpserver.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qudpsocket.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qsslcertificateextension.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qsslcipher.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qsslellipticcurve.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QHash \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qsslkey.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtNetwork/qtnetworkversion.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qjsvalueiterator.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqml.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlprivate.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlparserstatus.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlpropertyvaluesource.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmllist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlabstracturlinterceptor.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlcomponent.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlexpression.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlscriptstring.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlextensioninterface.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlextensionplugin.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlfile.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlfileselector.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/QQmlEngine \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlincubator.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlnetworkaccessmanagerfactory.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlproperty.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qqmlpropertymap.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtQml/qtqmlversion.h \
		login.h \
		signup.h \
		changepassword.h \
		csvrw.h \
		validation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

signup.o: signup.cpp signup.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QObject \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnamespace.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobal.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qconfig.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfeatures.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsystemdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qprocessordetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcompilerdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypeinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypetraits.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsysinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlogging.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qflags.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbasicatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qgenericatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_cxx11.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_gcc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_msvc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv7.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv6.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv5.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_ia64.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_mips.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_x86.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_unix.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobalstatic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmutex.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnumeric.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstring.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qchar.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qrefcount.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qarraydata.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringbuilder.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qalgorithms.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qiterator.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearraylist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qregexp.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringmatcher.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcoreevent.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qscopedpointer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmetatype.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvarlengtharray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcontainerfwd.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qisenum.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QDebug \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qdebug.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qhash.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qpair.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmap.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtextstream.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qiodevice.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlocale.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvariant.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qshareddata.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvector.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qpoint.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qset.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o signup.o signup.cpp

login.o: login.cpp login.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QObject \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnamespace.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobal.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qconfig.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfeatures.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsystemdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qprocessordetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcompilerdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypeinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypetraits.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsysinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlogging.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qflags.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbasicatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qgenericatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_cxx11.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_gcc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_msvc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv7.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv6.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv5.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_ia64.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_mips.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_x86.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_unix.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobalstatic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmutex.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnumeric.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstring.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qchar.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qrefcount.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qarraydata.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringbuilder.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qalgorithms.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qiterator.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearraylist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qregexp.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringmatcher.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcoreevent.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qscopedpointer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmetatype.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvarlengtharray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcontainerfwd.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qisenum.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QDebug \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qdebug.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qhash.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qpair.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmap.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtextstream.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qiodevice.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlocale.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvariant.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qshareddata.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvector.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qpoint.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qset.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o login.cpp

validation.o: validation.cpp validation.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QObject \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnamespace.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobal.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qconfig.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfeatures.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsystemdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qprocessordetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcompilerdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypeinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypetraits.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsysinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlogging.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qflags.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbasicatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qgenericatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_cxx11.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_gcc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_msvc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv7.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv6.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv5.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_ia64.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_mips.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_x86.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_unix.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobalstatic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmutex.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnumeric.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstring.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qchar.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qrefcount.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qarraydata.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringbuilder.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qalgorithms.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qiterator.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearraylist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qregexp.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringmatcher.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcoreevent.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qscopedpointer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmetatype.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvarlengtharray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcontainerfwd.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qisenum.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QString \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QDebug \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qdebug.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qhash.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qpair.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmap.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtextstream.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qiodevice.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlocale.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvariant.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qshareddata.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvector.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qpoint.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qset.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcontiguouscache.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QRegularExpression \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qregularexpression.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o validation.o validation.cpp

csvrw.o: csvrw.cpp csvrw.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QObject \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnamespace.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobal.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qconfig.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfeatures.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsystemdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qprocessordetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcompilerdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypeinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypetraits.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsysinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlogging.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qflags.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbasicatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qgenericatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_cxx11.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_gcc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_msvc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv7.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv6.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv5.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_ia64.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_mips.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_x86.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_unix.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobalstatic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmutex.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnumeric.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstring.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qchar.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qrefcount.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qarraydata.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringbuilder.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qalgorithms.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qiterator.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearraylist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qregexp.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringmatcher.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcoreevent.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qscopedpointer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmetatype.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvarlengtharray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcontainerfwd.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qisenum.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QString \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QDebug \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qdebug.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qhash.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qpair.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmap.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtextstream.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qiodevice.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlocale.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvariant.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qshareddata.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvector.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qpoint.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qset.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcontiguouscache.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QFile \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfile.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfiledevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o csvrw.o csvrw.cpp

changepassword.o: changepassword.cpp changepassword.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QObject \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnamespace.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobal.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qconfig.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qfeatures.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsystemdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qprocessordetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcompilerdetection.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypeinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtypetraits.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qsysinfo.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlogging.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qflags.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbasicatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qgenericatomic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_cxx11.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_gcc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_msvc.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv7.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv6.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_armv5.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_ia64.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_mips.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_x86.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qatomic_unix.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qglobalstatic.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmutex.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qnumeric.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstring.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qchar.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qrefcount.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qarraydata.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringbuilder.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qalgorithms.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qiterator.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qbytearraylist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringlist.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qregexp.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qstringmatcher.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcoreevent.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qscopedpointer.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmetatype.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvarlengtharray.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcontainerfwd.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qisenum.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qobject_impl.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/QDebug \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qdebug.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qhash.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qpair.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qmap.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qtextstream.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qiodevice.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qlocale.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvariant.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qshareddata.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qvector.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qpoint.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qset.h \
		../../Qt5.5.1_Desktop32Bit_out2/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o changepassword.o changepassword.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_signup.o: moc_signup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_signup.o moc_signup.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_validation.o: moc_validation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_validation.o moc_validation.cpp

moc_csvrw.o: moc_csvrw.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_csvrw.o moc_csvrw.cpp

moc_changepassword.o: moc_changepassword.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_changepassword.o moc_changepassword.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/finalNewBe/bin || mkdir -p $(INSTALL_ROOT)/opt/finalNewBe/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/finalNewBe/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/finalNewBe/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/finalNewBe/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/finalNewBe/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

